// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LAB11TRPZ.Models;

public partial class PrinterType
{
    public int PrinterTypeId { get; set; }

    public string TypeName { get; set; }

    public string Description { get; set; }

    public virtual ICollection<Printer> Printers { get; set; } = new List<Printer>();
}