// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LAB11TRPZ.Models;

public partial class PrinterModel
{
    public int PrinterModelId { get; set; }

    public string ModelName { get; set; }

    public string Manufacturer { get; set; }

    public virtual ICollection<Printer> Printers { get; set; } = new List<Printer>();
}