// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LAB11TRPZ.Models;

public partial class Printer
{
    public int PrinterId { get; set; }

    public string SerialNumber { get; set; }

    public int? PrinterModelId { get; set; }

    public int? PrinterTypeId { get; set; }

    public DateTime? ReleaseDate { get; set; }

    public virtual PrinterModel PrinterModel { get; set; }

    public virtual PrinterType PrinterType { get; set; }
}